### ISSUE TITLE
Android via

### ISSUE THREAD

**Issue by NathanWalker** [sean-perkins/nativescript-confettiview#1]
You guys considered using https://github.com/jinatonic/confetti for Android?

/cc @bradmartin

**Comment by bradmartin** [comment]
I might have shown this to Mr. Perkins months ago. I can prob throw it together in a couple hours next week sometime. Definitely up for grabs if someone else wants it though :)

**Comment by EddyVerbruggen** [comment]
This was just released for Android, could be a nice candidate as well: https://github.com/DanielMartinus/Konfetti

**Comment by sean-perkins** [comment]
Android support has been added (just forgot to close this issue). Thanks for adding it Nathan!
