### ISSUE TITLE
Upgrade to latest Swift version

### ISSUE THREAD

**Issue by jlooper** [sean-perkins/nativescript-confettiview#2]
hi, before I can run the demo, I am prompted to upgrade to the latest Swift version. Would it be possible to upgrade the plugin? 

Also I'd really love to have an Android version of this... ping ping @triniwiz

**Comment by triniwiz** [comment]
https://github.com/sudeepag/SAConfettiView/issues/25 suggests using  the following pod
`pod 'SAConfettiView', :git => 'https://github.com/gokhanakkurt/SAConfettiView', :branch => 'swift3'`
